version: "3.3"

services:
  
  api:
      # container_name: api
      image: api-trello
      # working_dir: /app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '4000:4000'
      # command: npm run build && nodemon dist/server.js
      init: true
      restart: always
      volumes:
        - .:/app
         - app-logs:/var/log/app
      depends_on:
        - postgres
      # links: 
      #       - "postgres:database"
      networks:
      - trello-clone
      
  postgres:
      image: postgres:alpine
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=admin2021
        - POSTGRES_DB=trello-clone
      networks:
        trello-clone:
          aliases:
            - database
      

networks:
  trello-clone:
    driver: bridge

volumes:
  pgdata:
  app-logs:
    external: true