version: "3.3"

services:
  
  api:
      # container_name: api
      image: api-trello
      env_file: .env
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        # - '4000:4000'
        - ${PORT}:${PORT}
      # command: npm run build && nodemon dist/server.js
      # init: true
      restart: always
      logging:
        driver: json-file
      volumes:
        - ./src:/usr/app/src
        - ./logs:/usr/app/logs
        - ./nodemon.json:/usr/app/nodemon.json
        # - ./logs:/var/lib/docker/containers/
      depends_on:
        - postgres
      # links: 
      #       - "postgres:database"
      networks:
      - trello_clone_network
      
  postgres:
      image: postgres-trello
      build: ./dataBase/docker
      restart: always
      ports:
        # - "5432:5432"
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
        - ./dataBase/pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      networks:
      - trello_clone_network
        # trello_clone_network:
        #   aliases:
        #     - postgres
      

networks:
  trello_clone_network:
    driver: bridge

volumes:
  pgdata:
  logs:
    # external: true