### USERS ROUTES

### GET ALL USERS
GET http://localhost:4000/users HTTP/1.1

### GET SINGLE USER
GET http://localhost:4000/users/d1be5e28-7e4c-43cb-b4fd-6fbb3af29c7c HTTP/1.1

### ADD NEW USER
POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
    "name": "TEST_NEWNEW_USER",
    "login": "test_user",
    "password": "T35t_P@55w0rd"  
}

### DELETE SINGLE USER
DELETE http://localhost:4000/users/d1be5e28-7e4c-43cb-b4fd-6fbb3af29c7c HTTP/1.1

### UPDATE SINGLE USER
PUT http://localhost:4000/users/34d1e35a-24ea-4848-929f-1fc1bfdd2e2b  HTTP/1.1
Content-Type: application/json

{
    "name": "updated_USER",
    "login": "new_LOGIN",
    "password": "FFF_P@55w0rd"  
}


### BOARDS ROUTES

### GET ALL BOARDS
GET http://localhost:4000/boards HTTP/1.1

### GET SINGLE BOARD
GET http://localhost:4000/boards/b06eca8f-1d06-4b8a-8afa-f2970a76aab HTTP/1.1

### ADD NEW BOARD
POST http://localhost:4000/boards HTTP/1.1
Content-Type: application/json

{
  "title": "NEW BOARD",
  "columns": [
    {
      "id": "d6358dc1-02a1-4fe8-b1ef-e86b5ecf0aa5",
      "title": "column one",
      "order": 0
    }
  ]
}

### DELETE SINGLE BOARD
DELETE http://localhost:4000/boards/bd99b620-cc9d-40dc-9222-7d506abf138a HTTP/1.1

### UPDATE SINGLE BOARD
PUT http://localhost:4000/boards/1  HTTP/1.1
Content-Type: application/json

{
  "title": "UPDATED BOARD",
  "columns": [
    {
      "id": "d6358dc1-02a1-4fe8-b1ef-e86b5ecf0aa9",
      "title": "column one",
      "order": 0
    },
    {
      "id":"ae41ff26-121e-4da8-afa3-f788abbd65ag",
      "title": "column TWO",
      "order": 1
    }
  ]
}


### TASKS ROUTES

### GET ALL TASKS
GET http://localhost:4000/boards/1/tasks HTTP/1.1

### GET SINGLE TASK
GET http://localhost:4000/boards/1/tasks/2e4a38db-3292-45da-9399-c320096ab98d HTTP/1.1

### ADD NEW TASK
POST http://localhost:4000/boards/fa0e8b0a-7cdb-4336-ad7e-eb29f1961a49/tasks HTTP/1.1
Content-Type: application/json

{
  
   "title": "TITLE for NEW TASK",
   "order": 2,
   "description": "Lorem ipsum",
   "userId": "c453d3e6-b0b1-4b44-bd43-a9d1190fd2g2",
   "columnId": "74ecd2b9-de8a-4ae6-998b-976781a0d97e",
   "boardId": null 
}

### DELETE SINGLE TASK
DELETE http://localhost:4000/boards/2/tasks/e705791b-99c7-41e4-8f4e-5872f5e1e6f3 HTTP/1.1

### UPDATE SINGLE TASK
PUT http://localhost:4000/boards/1/tasks/2e4a38db-3292-45da-9399-c320096ab98d  HTTP/1.1
Content-Type: application/json

{
  "title": "UPDATED TASK",  
  "order": 0,
  "description": "UPDATED Lorem ipsum",
  "userId": "1",
  "columnId": "1",
  "boardId": "1"

}